### ISSUE TITLE
Time synchronization fails with IP address, but works with domain names

### ISSUE THREAD

**Issue by nikoszagk** [earentir/ntpcl#2]
**Description:**
When attempting to synchronize time using an IP address as the server, the tool fails to establish a connection or complete the synchronization process. However, when the same server is provided as a domain name, the synchronization proceeds without issue. This indicates that the tool handles domain names properly but encounters an error when using IP addresses directly.

**Steps to Reproduce:**
1.  Login to the agent machine
2. ntpcl -s -n 216.239.35.0

**Expected Behavior:**
The tool should synchronize time successfully whether a domain name or an IP address is provided as the server.

**Actual Behavior:**
Time synchronization works with a domain name but fails with an IP address.

**Environment:**
- Tool Version: v0.4.13
- Operating System: Debian GNU/Linux 10 (buster) / Oracle Linux Server
- Network Setup: Local Area Network (LAN)

**Comment by earentir** [comment]
It should work with IP since [v0.4.13](https://github.com/earentir/ntpcl/releases/tag/v0.4.13), please check with a newer release :)

**Comment by nikoszagk** [comment]
Seems to be working now. Maybe i missed something in terminal
